# Generated by Django 3.1.4 on 2021-01-20 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0002_languagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dialect.', max_length=100, verbose_name='Dialect Name')),
                ('native_name', models.CharField(help_text="Name of the dialect and written in native of it's language.", max_length=100, verbose_name='Native Dialect Name')),
                ('description', models.TextField(blank=True, help_text='Description about the dialect.', verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialects', related_query_name='dialect', to=settings.AUTH_USER_MODEL, verbose_name='Creator Id')),
            ],
            options={
                'verbose_name': 'dialect',
                'verbose_name_plural': 'dialects',
            },
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, help_text='Description about the language.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_639_1',
            field=models.CharField(help_text='more info in <a href="https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes" target="_blank">Wikipedia</a>.', max_length=2, unique=True, verbose_name='ISO 639-1'),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_639_2',
            field=models.CharField(help_text='more info in <a href="https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes" target="_blank">Wikipedia</a>.', max_length=3, unique=True, verbose_name='ISO 639-2'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Name of the language.', max_length=100, unique=True, verbose_name='Language Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='native_name',
            field=models.CharField(help_text="Name of the language and written in native of it's language.", max_length=100, unique=True, verbose_name='Native Language Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp'),
        ),
        migrations.AlterField(
            model_name='languagehistory',
            name='description',
            field=models.TextField(blank=True, help_text='Description about the language.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='languagehistory',
            name='iso_639_1',
            field=models.CharField(help_text='more info in <a href="https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes" target="_blank">Wikipedia</a>.', max_length=2, verbose_name='ISO 639-1'),
        ),
        migrations.AlterField(
            model_name='languagehistory',
            name='iso_639_2',
            field=models.CharField(help_text='more info in <a href="https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes" target="_blank">Wikipedia</a>.', max_length=3, verbose_name='ISO 639-2'),
        ),
        migrations.AlterField(
            model_name='languagehistory',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_histories', related_query_name='language_history', to='language.language', verbose_name='Language Id'),
        ),
        migrations.AlterField(
            model_name='languagehistory',
            name='name',
            field=models.CharField(help_text='Name of the language.', max_length=100, verbose_name='Language Name'),
        ),
        migrations.AlterField(
            model_name='languagehistory',
            name='native_name',
            field=models.CharField(help_text="Name of language and written in native of it's Language", max_length=100, verbose_name='Native Language Name'),
        ),
        migrations.AlterField(
            model_name='languagehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Edited Timestamp'),
        ),
        migrations.CreateModel(
            name='DialectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dialect.', max_length=100, verbose_name='Dialect Name')),
                ('native_name', models.CharField(help_text="Name of the dialect and written in native of it's language.", max_length=100, verbose_name='Native Dialect Name')),
                ('description', models.TextField(blank=True, help_text='Description about the dialect.', verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Edited Timestamp')),
                ('dialect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialect_histories', related_query_name='dialect_history', to='language.dialect', verbose_name='Dialect Id')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialect_histories', related_query_name='dialect_history', to=settings.AUTH_USER_MODEL, verbose_name='Editor Id')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialect_histories', related_query_name='dialect_history', to='language.language', verbose_name='Language Id')),
                ('super_dialect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_dialect_histories', related_query_name='sub_dialect_history', to='language.dialect', verbose_name='Super Dialect Id')),
            ],
            options={
                'verbose_name': 'dialect history',
                'verbose_name_plural': 'dialect histories',
            },
        ),
        migrations.AddField(
            model_name='dialect',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialects', related_query_name='dialect', to='language.language', verbose_name='Language Id'),
        ),
        migrations.AddField(
            model_name='dialect',
            name='super_dialect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_dialects', related_query_name='sub_dialect', to='language.dialect', verbose_name='Super Dialect Id'),
        ),
        migrations.AddConstraint(
            model_name='dialect',
            constraint=models.UniqueConstraint(fields=('language', 'name'), name='Unique dialect to a language'),
        ),
    ]
